apiVersion: v1
kind: Service
metadata:
  name: casewebportal-svc
  namespace: greencompute
  labels:
    app: portal-app-bc-caseportal-app
spec:
  type: NodePort
  ports:
  - port: 6100
    targetPort: 6100
    protocol: TCP
    name: http
  selector:
    app: portal-app-bc-caseportal-app
