apiVersion: v1
kind: ConfigMap
metadata:
  name: casewebportal-bc-caseportal-app
  namespace: greencompute
  labels:
    chart: bc-caseportal-app-0.0.6
data:
  config.json: |+
    {
        "secureGateway" : {
          "url":"https://cap-sg-prd-5.integration.ibmcloud.com:16582"
        },
        "apiGateway" :{
          "hostUrl": "https://172.16.50.8",
          "url": "/csplab/sb/iib-inventory-api",
          "xibmclientid": "59a3a4cb-db42-40ff-bf22-b8c3b5e9eedb",
          "xibmclientid0": "5d2a6edb-793d-4193-b9b0-0a087ea6c123"
        },
        "inventoryDAL" :{
          "url": "http://green.csplab.local/inventory/ws"
        },
        "conversationBroker" :{
          "url":"https://refarch-wcs-broker.mybluemix.net/api/conversation"
        },
        "supportConversation" :{
          "version" : "v1",
          "versionDate":"2017-05-26",
          "username":"291d9397-073f-46d9-b0d2-11b54e6ae533",
          "password":"aDFBIIPYkQlD",
          "conversationId":"SupportHelpDesk",
          "workspace":"1a3b01f3-4757-444d-a933-a1e648babfc1",
          "usePersistence": false
        },

        "watsonAssistant" :{
          "version" : "v1",
          "versionDate":"2017-05-26",
          "username":"291d9397-073f-46d9-b0d2-11b54e6ae533",
          "password":"aDFBIIPYkQlD",
          "conversationId":"Complex Relocation",
          "workspace":"a97a02e3-d3c3-48de-8e64-20502819e582",
          "usePersistence": false
        },

        "customerAPI":{
            "url": "http://green.csplab.local/caseserv/api/v1"
        },
        "odm" : {
          "hostname": "172.16.40.132",
          "port": 32764,
          "protocol": "http:",
          "path": "/DecisionService/rest/v1/ProductRecommendationRuleApp/1.0/ProductRecommendation/1.0/WADL",
          "authtoken":"Basic cmVzQWRtaW46MWpldzFyNTc1enU1ZA=="
        },
        "toneAnalyzer":{
            "url": "https://gateway.watsonplatform.net/tone-analyzer/api",
            "versionDate": "2017-09-21",
            "username": "3edad474-c386-429e-84e7-9097fcd3e328",
            "password": "zXfeNcN0zWQK"
        },
        "scoringService":{
          "type":"WML",
          "baseUrl": "https://ibm-watson-ml.mybluemix.net",
          "instance": "/v3/wml_instances/e947215d-9d96-48d0-bdce-d50e9431ca80/published_models/face8a83-b3e2-4cee-9b5e-76aaf01b3b78/deployments/3233874f-e8bd-459d-afa3-ab1d9ca148f9/online",
          "username": "02f481c2-7717-4e79-b60f-3c1214b5f374",
          "password": "f2f9349b-ebb5-4dfd-9318-94615a06fffb"
        },
        "dbCredentials" : {
          "url": "https://01bcc074-b3a0-4b07-93c6-eade6fb3ce50-bluemix:cd68d33a28d499bc6211810a56a0b99393a699190630f7811c438149be944500@01bcc074-b3a0-4b07-93c6-eade6fb3ce50-bluemix.cloudant.com"
        },

        "mode" : "all",
        "debug": true,
        "environment" : "private",
        "port" : 6100,
        "version": "v0.0.6"
    }
