apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: casewebportal
  namespace: default
  labels:
    app: casewebportal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: casewebportal
    spec:
      containers:
      - name: casewebportal
        image: mycluster:8500/default/casewebportal:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6100
        volumeMounts:
        - name: config
          mountPath: /caseportal/server/config.json
          subPath: config.json
      volumes:
      - name: config
        configMap:
          name: casewebportal
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: admin.registrykey
        - name: default-token-45n44
      schedulerName: default-scheduler
